apiVersion: v1
kind: ConfigMap
metadata:
  name: tournament-service-config
data:
  PORT: "4004"
  MONGO_URL: "mongodb://admin:password123@mongo-service.dev.svc.cluster.local:27017/tournament_db?authSource=admin"
  REDIS_URL: "redis://redis-service.dev.svc.cluster.local:6379"
